/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as PrivacidadRouteImport } from './routes/privacidad'
import { Route as PortalRouteImport } from './routes/portal'
import { Route as LoginRouteImport } from './routes/login'
import { Route as AuthenticatedRouteImport } from './routes/_authenticated'
import { Route as IndexRouteImport } from './routes/index'
import { Route as PortalIndexRouteImport } from './routes/portal.index'
import { Route as TQrTokenRouteImport } from './routes/t.$qrToken'
import { Route as PortalInformesRouteImport } from './routes/portal.informes'
import { Route as PortalIncidenciasRouteImport } from './routes/portal.incidencias'
import { Route as PortalEventosRouteImport } from './routes/portal.eventos'
import { Route as FFormSlugRouteImport } from './routes/f.$formSlug'
import { Route as ESlugRouteImport } from './routes/e.$slug'
import { Route as CTokenRouteImport } from './routes/c.$token'
import { Route as AuthenticatedUsuariosRouteImport } from './routes/_authenticated/usuarios'
import { Route as AuthenticatedSolicitudesRouteImport } from './routes/_authenticated/solicitudes'
import { Route as AuthenticatedSesionesRouteImport } from './routes/_authenticated/sesiones'
import { Route as AuthenticatedPersonasRouteImport } from './routes/_authenticated/personas'
import { Route as AuthenticatedLogsRouteImport } from './routes/_authenticated/logs'
import { Route as AuthenticatedLegalRouteImport } from './routes/_authenticated/legal'
import { Route as AuthenticatedInformesRouteImport } from './routes/_authenticated/informes'
import { Route as AuthenticatedIncidenciasRouteImport } from './routes/_authenticated/incidencias'
import { Route as AuthenticatedImportacionesRouteImport } from './routes/_authenticated/importaciones'
import { Route as AuthenticatedDisenoEntradasRouteImport } from './routes/_authenticated/diseno-entradas'
import { Route as AuthenticatedDashboardRouteImport } from './routes/_authenticated/dashboard'
import { Route as AuthenticatedControlAccesoRouteImport } from './routes/_authenticated/control-acceso'
import { Route as AuthenticatedComunicacionesRouteImport } from './routes/_authenticated/comunicaciones'
import { Route as AuthenticatedClientesRouteImport } from './routes/_authenticated/clientes'
import { Route as AuthenticatedBrandingRouteImport } from './routes/_authenticated/branding'
import { Route as PortalEventosIndexRouteImport } from './routes/portal.eventos.index'
import { Route as AuthenticatedEventosIndexRouteImport } from './routes/_authenticated/eventos.index'
import { Route as PortalEventosEventIdRouteImport } from './routes/portal.eventos.$eventId'
import { Route as OgCTokenRouteImport } from './routes/og.c.$token'
import { Route as ESlugInscripcionRouteImport } from './routes/e.$slug.inscripcion'
import { Route as ESlugGraciasRouteImport } from './routes/e.$slug.gracias'
import { Route as ESlugCompletoRouteImport } from './routes/e.$slug.completo'
import { Route as ESlugCerradoRouteImport } from './routes/e.$slug.cerrado'
import { Route as CTokenEntradaRouteImport } from './routes/c.$token.entrada'
import { Route as CTokenCancelarRouteImport } from './routes/c.$token.cancelar'
import { Route as CTokenCanceladaRouteImport } from './routes/c.$token.cancelada'
import { Route as AuthenticatedSolicitudesParticipantIdRouteImport } from './routes/_authenticated/solicitudes.$participantId'
import { Route as AuthenticatedInformesEventIdRouteImport } from './routes/_authenticated/informes.$eventId'
import { Route as AuthenticatedImportacionesNuevaRouteImport } from './routes/_authenticated/importaciones.nueva'
import { Route as AuthenticatedImportacionesBatchIdRouteImport } from './routes/_authenticated/importaciones.$batchId'
import { Route as AuthenticatedEventosNuevoRouteImport } from './routes/_authenticated/eventos.nuevo'
import { Route as AuthenticatedEventosEventIdRouteImport } from './routes/_authenticated/eventos.$eventId'
import { Route as AuthenticatedControlAccesoSessionIdRouteImport } from './routes/_authenticated/control-acceso.$sessionId'
import { Route as AuthenticatedComunicacionesEnvioRouteImport } from './routes/_authenticated/comunicaciones.envio'
import { Route as AuthenticatedComunicacionesColaRouteImport } from './routes/_authenticated/comunicaciones.cola'
import { Route as AuthenticatedEventosEventIdEditarRouteImport } from './routes/_authenticated/eventos.$eventId.editar'
import { Route as AuthenticatedEventosEventIdSesionesNuevaRouteImport } from './routes/_authenticated/eventos.$eventId.sesiones.nueva'
import { Route as AuthenticatedEventosEventIdSesionesSessionIdRouteImport } from './routes/_authenticated/eventos.$eventId.sesiones.$sessionId'

const PrivacidadRoute = PrivacidadRouteImport.update({
  id: '/privacidad',
  path: '/privacidad',
  getParentRoute: () => rootRouteImport,
} as any)
const PortalRoute = PortalRouteImport.update({
  id: '/portal',
  path: '/portal',
  getParentRoute: () => rootRouteImport,
} as any)
const LoginRoute = LoginRouteImport.update({
  id: '/login',
  path: '/login',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthenticatedRoute = AuthenticatedRouteImport.update({
  id: '/_authenticated',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const PortalIndexRoute = PortalIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => PortalRoute,
} as any)
const TQrTokenRoute = TQrTokenRouteImport.update({
  id: '/t/$qrToken',
  path: '/t/$qrToken',
  getParentRoute: () => rootRouteImport,
} as any)
const PortalInformesRoute = PortalInformesRouteImport.update({
  id: '/informes',
  path: '/informes',
  getParentRoute: () => PortalRoute,
} as any)
const PortalIncidenciasRoute = PortalIncidenciasRouteImport.update({
  id: '/incidencias',
  path: '/incidencias',
  getParentRoute: () => PortalRoute,
} as any)
const PortalEventosRoute = PortalEventosRouteImport.update({
  id: '/eventos',
  path: '/eventos',
  getParentRoute: () => PortalRoute,
} as any)
const FFormSlugRoute = FFormSlugRouteImport.update({
  id: '/f/$formSlug',
  path: '/f/$formSlug',
  getParentRoute: () => rootRouteImport,
} as any)
const ESlugRoute = ESlugRouteImport.update({
  id: '/e/$slug',
  path: '/e/$slug',
  getParentRoute: () => rootRouteImport,
} as any)
const CTokenRoute = CTokenRouteImport.update({
  id: '/c/$token',
  path: '/c/$token',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthenticatedUsuariosRoute = AuthenticatedUsuariosRouteImport.update({
  id: '/usuarios',
  path: '/usuarios',
  getParentRoute: () => AuthenticatedRoute,
} as any)
const AuthenticatedSolicitudesRoute =
  AuthenticatedSolicitudesRouteImport.update({
    id: '/solicitudes',
    path: '/solicitudes',
    getParentRoute: () => AuthenticatedRoute,
  } as any)
const AuthenticatedSesionesRoute = AuthenticatedSesionesRouteImport.update({
  id: '/sesiones',
  path: '/sesiones',
  getParentRoute: () => AuthenticatedRoute,
} as any)
const AuthenticatedPersonasRoute = AuthenticatedPersonasRouteImport.update({
  id: '/personas',
  path: '/personas',
  getParentRoute: () => AuthenticatedRoute,
} as any)
const AuthenticatedLogsRoute = AuthenticatedLogsRouteImport.update({
  id: '/logs',
  path: '/logs',
  getParentRoute: () => AuthenticatedRoute,
} as any)
const AuthenticatedLegalRoute = AuthenticatedLegalRouteImport.update({
  id: '/legal',
  path: '/legal',
  getParentRoute: () => AuthenticatedRoute,
} as any)
const AuthenticatedInformesRoute = AuthenticatedInformesRouteImport.update({
  id: '/informes',
  path: '/informes',
  getParentRoute: () => AuthenticatedRoute,
} as any)
const AuthenticatedIncidenciasRoute =
  AuthenticatedIncidenciasRouteImport.update({
    id: '/incidencias',
    path: '/incidencias',
    getParentRoute: () => AuthenticatedRoute,
  } as any)
const AuthenticatedImportacionesRoute =
  AuthenticatedImportacionesRouteImport.update({
    id: '/importaciones',
    path: '/importaciones',
    getParentRoute: () => AuthenticatedRoute,
  } as any)
const AuthenticatedDisenoEntradasRoute =
  AuthenticatedDisenoEntradasRouteImport.update({
    id: '/diseno-entradas',
    path: '/diseno-entradas',
    getParentRoute: () => AuthenticatedRoute,
  } as any)
const AuthenticatedDashboardRoute = AuthenticatedDashboardRouteImport.update({
  id: '/dashboard',
  path: '/dashboard',
  getParentRoute: () => AuthenticatedRoute,
} as any)
const AuthenticatedControlAccesoRoute =
  AuthenticatedControlAccesoRouteImport.update({
    id: '/control-acceso',
    path: '/control-acceso',
    getParentRoute: () => AuthenticatedRoute,
  } as any)
const AuthenticatedComunicacionesRoute =
  AuthenticatedComunicacionesRouteImport.update({
    id: '/comunicaciones',
    path: '/comunicaciones',
    getParentRoute: () => AuthenticatedRoute,
  } as any)
const AuthenticatedClientesRoute = AuthenticatedClientesRouteImport.update({
  id: '/clientes',
  path: '/clientes',
  getParentRoute: () => AuthenticatedRoute,
} as any)
const AuthenticatedBrandingRoute = AuthenticatedBrandingRouteImport.update({
  id: '/branding',
  path: '/branding',
  getParentRoute: () => AuthenticatedRoute,
} as any)
const PortalEventosIndexRoute = PortalEventosIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => PortalEventosRoute,
} as any)
const AuthenticatedEventosIndexRoute =
  AuthenticatedEventosIndexRouteImport.update({
    id: '/eventos/',
    path: '/eventos/',
    getParentRoute: () => AuthenticatedRoute,
  } as any)
const PortalEventosEventIdRoute = PortalEventosEventIdRouteImport.update({
  id: '/$eventId',
  path: '/$eventId',
  getParentRoute: () => PortalEventosRoute,
} as any)
const OgCTokenRoute = OgCTokenRouteImport.update({
  id: '/og/c/$token',
  path: '/og/c/$token',
  getParentRoute: () => rootRouteImport,
} as any)
const ESlugInscripcionRoute = ESlugInscripcionRouteImport.update({
  id: '/inscripcion',
  path: '/inscripcion',
  getParentRoute: () => ESlugRoute,
} as any)
const ESlugGraciasRoute = ESlugGraciasRouteImport.update({
  id: '/gracias',
  path: '/gracias',
  getParentRoute: () => ESlugRoute,
} as any)
const ESlugCompletoRoute = ESlugCompletoRouteImport.update({
  id: '/completo',
  path: '/completo',
  getParentRoute: () => ESlugRoute,
} as any)
const ESlugCerradoRoute = ESlugCerradoRouteImport.update({
  id: '/cerrado',
  path: '/cerrado',
  getParentRoute: () => ESlugRoute,
} as any)
const CTokenEntradaRoute = CTokenEntradaRouteImport.update({
  id: '/entrada',
  path: '/entrada',
  getParentRoute: () => CTokenRoute,
} as any)
const CTokenCancelarRoute = CTokenCancelarRouteImport.update({
  id: '/cancelar',
  path: '/cancelar',
  getParentRoute: () => CTokenRoute,
} as any)
const CTokenCanceladaRoute = CTokenCanceladaRouteImport.update({
  id: '/cancelada',
  path: '/cancelada',
  getParentRoute: () => CTokenRoute,
} as any)
const AuthenticatedSolicitudesParticipantIdRoute =
  AuthenticatedSolicitudesParticipantIdRouteImport.update({
    id: '/$participantId',
    path: '/$participantId',
    getParentRoute: () => AuthenticatedSolicitudesRoute,
  } as any)
const AuthenticatedInformesEventIdRoute =
  AuthenticatedInformesEventIdRouteImport.update({
    id: '/$eventId',
    path: '/$eventId',
    getParentRoute: () => AuthenticatedInformesRoute,
  } as any)
const AuthenticatedImportacionesNuevaRoute =
  AuthenticatedImportacionesNuevaRouteImport.update({
    id: '/nueva',
    path: '/nueva',
    getParentRoute: () => AuthenticatedImportacionesRoute,
  } as any)
const AuthenticatedImportacionesBatchIdRoute =
  AuthenticatedImportacionesBatchIdRouteImport.update({
    id: '/$batchId',
    path: '/$batchId',
    getParentRoute: () => AuthenticatedImportacionesRoute,
  } as any)
const AuthenticatedEventosNuevoRoute =
  AuthenticatedEventosNuevoRouteImport.update({
    id: '/eventos/nuevo',
    path: '/eventos/nuevo',
    getParentRoute: () => AuthenticatedRoute,
  } as any)
const AuthenticatedEventosEventIdRoute =
  AuthenticatedEventosEventIdRouteImport.update({
    id: '/eventos/$eventId',
    path: '/eventos/$eventId',
    getParentRoute: () => AuthenticatedRoute,
  } as any)
const AuthenticatedControlAccesoSessionIdRoute =
  AuthenticatedControlAccesoSessionIdRouteImport.update({
    id: '/$sessionId',
    path: '/$sessionId',
    getParentRoute: () => AuthenticatedControlAccesoRoute,
  } as any)
const AuthenticatedComunicacionesEnvioRoute =
  AuthenticatedComunicacionesEnvioRouteImport.update({
    id: '/envio',
    path: '/envio',
    getParentRoute: () => AuthenticatedComunicacionesRoute,
  } as any)
const AuthenticatedComunicacionesColaRoute =
  AuthenticatedComunicacionesColaRouteImport.update({
    id: '/cola',
    path: '/cola',
    getParentRoute: () => AuthenticatedComunicacionesRoute,
  } as any)
const AuthenticatedEventosEventIdEditarRoute =
  AuthenticatedEventosEventIdEditarRouteImport.update({
    id: '/editar',
    path: '/editar',
    getParentRoute: () => AuthenticatedEventosEventIdRoute,
  } as any)
const AuthenticatedEventosEventIdSesionesNuevaRoute =
  AuthenticatedEventosEventIdSesionesNuevaRouteImport.update({
    id: '/sesiones/nueva',
    path: '/sesiones/nueva',
    getParentRoute: () => AuthenticatedEventosEventIdRoute,
  } as any)
const AuthenticatedEventosEventIdSesionesSessionIdRoute =
  AuthenticatedEventosEventIdSesionesSessionIdRouteImport.update({
    id: '/sesiones/$sessionId',
    path: '/sesiones/$sessionId',
    getParentRoute: () => AuthenticatedEventosEventIdRoute,
  } as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/login': typeof LoginRoute
  '/portal': typeof PortalRouteWithChildren
  '/privacidad': typeof PrivacidadRoute
  '/branding': typeof AuthenticatedBrandingRoute
  '/clientes': typeof AuthenticatedClientesRoute
  '/comunicaciones': typeof AuthenticatedComunicacionesRouteWithChildren
  '/control-acceso': typeof AuthenticatedControlAccesoRouteWithChildren
  '/dashboard': typeof AuthenticatedDashboardRoute
  '/diseno-entradas': typeof AuthenticatedDisenoEntradasRoute
  '/importaciones': typeof AuthenticatedImportacionesRouteWithChildren
  '/incidencias': typeof AuthenticatedIncidenciasRoute
  '/informes': typeof AuthenticatedInformesRouteWithChildren
  '/legal': typeof AuthenticatedLegalRoute
  '/logs': typeof AuthenticatedLogsRoute
  '/personas': typeof AuthenticatedPersonasRoute
  '/sesiones': typeof AuthenticatedSesionesRoute
  '/solicitudes': typeof AuthenticatedSolicitudesRouteWithChildren
  '/usuarios': typeof AuthenticatedUsuariosRoute
  '/c/$token': typeof CTokenRouteWithChildren
  '/e/$slug': typeof ESlugRouteWithChildren
  '/f/$formSlug': typeof FFormSlugRoute
  '/portal/eventos': typeof PortalEventosRouteWithChildren
  '/portal/incidencias': typeof PortalIncidenciasRoute
  '/portal/informes': typeof PortalInformesRoute
  '/t/$qrToken': typeof TQrTokenRoute
  '/portal/': typeof PortalIndexRoute
  '/comunicaciones/cola': typeof AuthenticatedComunicacionesColaRoute
  '/comunicaciones/envio': typeof AuthenticatedComunicacionesEnvioRoute
  '/control-acceso/$sessionId': typeof AuthenticatedControlAccesoSessionIdRoute
  '/eventos/$eventId': typeof AuthenticatedEventosEventIdRouteWithChildren
  '/eventos/nuevo': typeof AuthenticatedEventosNuevoRoute
  '/importaciones/$batchId': typeof AuthenticatedImportacionesBatchIdRoute
  '/importaciones/nueva': typeof AuthenticatedImportacionesNuevaRoute
  '/informes/$eventId': typeof AuthenticatedInformesEventIdRoute
  '/solicitudes/$participantId': typeof AuthenticatedSolicitudesParticipantIdRoute
  '/c/$token/cancelada': typeof CTokenCanceladaRoute
  '/c/$token/cancelar': typeof CTokenCancelarRoute
  '/c/$token/entrada': typeof CTokenEntradaRoute
  '/e/$slug/cerrado': typeof ESlugCerradoRoute
  '/e/$slug/completo': typeof ESlugCompletoRoute
  '/e/$slug/gracias': typeof ESlugGraciasRoute
  '/e/$slug/inscripcion': typeof ESlugInscripcionRoute
  '/og/c/$token': typeof OgCTokenRoute
  '/portal/eventos/$eventId': typeof PortalEventosEventIdRoute
  '/eventos/': typeof AuthenticatedEventosIndexRoute
  '/portal/eventos/': typeof PortalEventosIndexRoute
  '/eventos/$eventId/editar': typeof AuthenticatedEventosEventIdEditarRoute
  '/eventos/$eventId/sesiones/$sessionId': typeof AuthenticatedEventosEventIdSesionesSessionIdRoute
  '/eventos/$eventId/sesiones/nueva': typeof AuthenticatedEventosEventIdSesionesNuevaRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/login': typeof LoginRoute
  '/privacidad': typeof PrivacidadRoute
  '/branding': typeof AuthenticatedBrandingRoute
  '/clientes': typeof AuthenticatedClientesRoute
  '/comunicaciones': typeof AuthenticatedComunicacionesRouteWithChildren
  '/control-acceso': typeof AuthenticatedControlAccesoRouteWithChildren
  '/dashboard': typeof AuthenticatedDashboardRoute
  '/diseno-entradas': typeof AuthenticatedDisenoEntradasRoute
  '/importaciones': typeof AuthenticatedImportacionesRouteWithChildren
  '/incidencias': typeof AuthenticatedIncidenciasRoute
  '/informes': typeof AuthenticatedInformesRouteWithChildren
  '/legal': typeof AuthenticatedLegalRoute
  '/logs': typeof AuthenticatedLogsRoute
  '/personas': typeof AuthenticatedPersonasRoute
  '/sesiones': typeof AuthenticatedSesionesRoute
  '/solicitudes': typeof AuthenticatedSolicitudesRouteWithChildren
  '/usuarios': typeof AuthenticatedUsuariosRoute
  '/c/$token': typeof CTokenRouteWithChildren
  '/e/$slug': typeof ESlugRouteWithChildren
  '/f/$formSlug': typeof FFormSlugRoute
  '/portal/incidencias': typeof PortalIncidenciasRoute
  '/portal/informes': typeof PortalInformesRoute
  '/t/$qrToken': typeof TQrTokenRoute
  '/portal': typeof PortalIndexRoute
  '/comunicaciones/cola': typeof AuthenticatedComunicacionesColaRoute
  '/comunicaciones/envio': typeof AuthenticatedComunicacionesEnvioRoute
  '/control-acceso/$sessionId': typeof AuthenticatedControlAccesoSessionIdRoute
  '/eventos/$eventId': typeof AuthenticatedEventosEventIdRouteWithChildren
  '/eventos/nuevo': typeof AuthenticatedEventosNuevoRoute
  '/importaciones/$batchId': typeof AuthenticatedImportacionesBatchIdRoute
  '/importaciones/nueva': typeof AuthenticatedImportacionesNuevaRoute
  '/informes/$eventId': typeof AuthenticatedInformesEventIdRoute
  '/solicitudes/$participantId': typeof AuthenticatedSolicitudesParticipantIdRoute
  '/c/$token/cancelada': typeof CTokenCanceladaRoute
  '/c/$token/cancelar': typeof CTokenCancelarRoute
  '/c/$token/entrada': typeof CTokenEntradaRoute
  '/e/$slug/cerrado': typeof ESlugCerradoRoute
  '/e/$slug/completo': typeof ESlugCompletoRoute
  '/e/$slug/gracias': typeof ESlugGraciasRoute
  '/e/$slug/inscripcion': typeof ESlugInscripcionRoute
  '/og/c/$token': typeof OgCTokenRoute
  '/portal/eventos/$eventId': typeof PortalEventosEventIdRoute
  '/eventos': typeof AuthenticatedEventosIndexRoute
  '/portal/eventos': typeof PortalEventosIndexRoute
  '/eventos/$eventId/editar': typeof AuthenticatedEventosEventIdEditarRoute
  '/eventos/$eventId/sesiones/$sessionId': typeof AuthenticatedEventosEventIdSesionesSessionIdRoute
  '/eventos/$eventId/sesiones/nueva': typeof AuthenticatedEventosEventIdSesionesNuevaRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/_authenticated': typeof AuthenticatedRouteWithChildren
  '/login': typeof LoginRoute
  '/portal': typeof PortalRouteWithChildren
  '/privacidad': typeof PrivacidadRoute
  '/_authenticated/branding': typeof AuthenticatedBrandingRoute
  '/_authenticated/clientes': typeof AuthenticatedClientesRoute
  '/_authenticated/comunicaciones': typeof AuthenticatedComunicacionesRouteWithChildren
  '/_authenticated/control-acceso': typeof AuthenticatedControlAccesoRouteWithChildren
  '/_authenticated/dashboard': typeof AuthenticatedDashboardRoute
  '/_authenticated/diseno-entradas': typeof AuthenticatedDisenoEntradasRoute
  '/_authenticated/importaciones': typeof AuthenticatedImportacionesRouteWithChildren
  '/_authenticated/incidencias': typeof AuthenticatedIncidenciasRoute
  '/_authenticated/informes': typeof AuthenticatedInformesRouteWithChildren
  '/_authenticated/legal': typeof AuthenticatedLegalRoute
  '/_authenticated/logs': typeof AuthenticatedLogsRoute
  '/_authenticated/personas': typeof AuthenticatedPersonasRoute
  '/_authenticated/sesiones': typeof AuthenticatedSesionesRoute
  '/_authenticated/solicitudes': typeof AuthenticatedSolicitudesRouteWithChildren
  '/_authenticated/usuarios': typeof AuthenticatedUsuariosRoute
  '/c/$token': typeof CTokenRouteWithChildren
  '/e/$slug': typeof ESlugRouteWithChildren
  '/f/$formSlug': typeof FFormSlugRoute
  '/portal/eventos': typeof PortalEventosRouteWithChildren
  '/portal/incidencias': typeof PortalIncidenciasRoute
  '/portal/informes': typeof PortalInformesRoute
  '/t/$qrToken': typeof TQrTokenRoute
  '/portal/': typeof PortalIndexRoute
  '/_authenticated/comunicaciones/cola': typeof AuthenticatedComunicacionesColaRoute
  '/_authenticated/comunicaciones/envio': typeof AuthenticatedComunicacionesEnvioRoute
  '/_authenticated/control-acceso/$sessionId': typeof AuthenticatedControlAccesoSessionIdRoute
  '/_authenticated/eventos/$eventId': typeof AuthenticatedEventosEventIdRouteWithChildren
  '/_authenticated/eventos/nuevo': typeof AuthenticatedEventosNuevoRoute
  '/_authenticated/importaciones/$batchId': typeof AuthenticatedImportacionesBatchIdRoute
  '/_authenticated/importaciones/nueva': typeof AuthenticatedImportacionesNuevaRoute
  '/_authenticated/informes/$eventId': typeof AuthenticatedInformesEventIdRoute
  '/_authenticated/solicitudes/$participantId': typeof AuthenticatedSolicitudesParticipantIdRoute
  '/c/$token/cancelada': typeof CTokenCanceladaRoute
  '/c/$token/cancelar': typeof CTokenCancelarRoute
  '/c/$token/entrada': typeof CTokenEntradaRoute
  '/e/$slug/cerrado': typeof ESlugCerradoRoute
  '/e/$slug/completo': typeof ESlugCompletoRoute
  '/e/$slug/gracias': typeof ESlugGraciasRoute
  '/e/$slug/inscripcion': typeof ESlugInscripcionRoute
  '/og/c/$token': typeof OgCTokenRoute
  '/portal/eventos/$eventId': typeof PortalEventosEventIdRoute
  '/_authenticated/eventos/': typeof AuthenticatedEventosIndexRoute
  '/portal/eventos/': typeof PortalEventosIndexRoute
  '/_authenticated/eventos/$eventId/editar': typeof AuthenticatedEventosEventIdEditarRoute
  '/_authenticated/eventos/$eventId/sesiones/$sessionId': typeof AuthenticatedEventosEventIdSesionesSessionIdRoute
  '/_authenticated/eventos/$eventId/sesiones/nueva': typeof AuthenticatedEventosEventIdSesionesNuevaRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/login'
    | '/portal'
    | '/privacidad'
    | '/branding'
    | '/clientes'
    | '/comunicaciones'
    | '/control-acceso'
    | '/dashboard'
    | '/diseno-entradas'
    | '/importaciones'
    | '/incidencias'
    | '/informes'
    | '/legal'
    | '/logs'
    | '/personas'
    | '/sesiones'
    | '/solicitudes'
    | '/usuarios'
    | '/c/$token'
    | '/e/$slug'
    | '/f/$formSlug'
    | '/portal/eventos'
    | '/portal/incidencias'
    | '/portal/informes'
    | '/t/$qrToken'
    | '/portal/'
    | '/comunicaciones/cola'
    | '/comunicaciones/envio'
    | '/control-acceso/$sessionId'
    | '/eventos/$eventId'
    | '/eventos/nuevo'
    | '/importaciones/$batchId'
    | '/importaciones/nueva'
    | '/informes/$eventId'
    | '/solicitudes/$participantId'
    | '/c/$token/cancelada'
    | '/c/$token/cancelar'
    | '/c/$token/entrada'
    | '/e/$slug/cerrado'
    | '/e/$slug/completo'
    | '/e/$slug/gracias'
    | '/e/$slug/inscripcion'
    | '/og/c/$token'
    | '/portal/eventos/$eventId'
    | '/eventos/'
    | '/portal/eventos/'
    | '/eventos/$eventId/editar'
    | '/eventos/$eventId/sesiones/$sessionId'
    | '/eventos/$eventId/sesiones/nueva'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/login'
    | '/privacidad'
    | '/branding'
    | '/clientes'
    | '/comunicaciones'
    | '/control-acceso'
    | '/dashboard'
    | '/diseno-entradas'
    | '/importaciones'
    | '/incidencias'
    | '/informes'
    | '/legal'
    | '/logs'
    | '/personas'
    | '/sesiones'
    | '/solicitudes'
    | '/usuarios'
    | '/c/$token'
    | '/e/$slug'
    | '/f/$formSlug'
    | '/portal/incidencias'
    | '/portal/informes'
    | '/t/$qrToken'
    | '/portal'
    | '/comunicaciones/cola'
    | '/comunicaciones/envio'
    | '/control-acceso/$sessionId'
    | '/eventos/$eventId'
    | '/eventos/nuevo'
    | '/importaciones/$batchId'
    | '/importaciones/nueva'
    | '/informes/$eventId'
    | '/solicitudes/$participantId'
    | '/c/$token/cancelada'
    | '/c/$token/cancelar'
    | '/c/$token/entrada'
    | '/e/$slug/cerrado'
    | '/e/$slug/completo'
    | '/e/$slug/gracias'
    | '/e/$slug/inscripcion'
    | '/og/c/$token'
    | '/portal/eventos/$eventId'
    | '/eventos'
    | '/portal/eventos'
    | '/eventos/$eventId/editar'
    | '/eventos/$eventId/sesiones/$sessionId'
    | '/eventos/$eventId/sesiones/nueva'
  id:
    | '__root__'
    | '/'
    | '/_authenticated'
    | '/login'
    | '/portal'
    | '/privacidad'
    | '/_authenticated/branding'
    | '/_authenticated/clientes'
    | '/_authenticated/comunicaciones'
    | '/_authenticated/control-acceso'
    | '/_authenticated/dashboard'
    | '/_authenticated/diseno-entradas'
    | '/_authenticated/importaciones'
    | '/_authenticated/incidencias'
    | '/_authenticated/informes'
    | '/_authenticated/legal'
    | '/_authenticated/logs'
    | '/_authenticated/personas'
    | '/_authenticated/sesiones'
    | '/_authenticated/solicitudes'
    | '/_authenticated/usuarios'
    | '/c/$token'
    | '/e/$slug'
    | '/f/$formSlug'
    | '/portal/eventos'
    | '/portal/incidencias'
    | '/portal/informes'
    | '/t/$qrToken'
    | '/portal/'
    | '/_authenticated/comunicaciones/cola'
    | '/_authenticated/comunicaciones/envio'
    | '/_authenticated/control-acceso/$sessionId'
    | '/_authenticated/eventos/$eventId'
    | '/_authenticated/eventos/nuevo'
    | '/_authenticated/importaciones/$batchId'
    | '/_authenticated/importaciones/nueva'
    | '/_authenticated/informes/$eventId'
    | '/_authenticated/solicitudes/$participantId'
    | '/c/$token/cancelada'
    | '/c/$token/cancelar'
    | '/c/$token/entrada'
    | '/e/$slug/cerrado'
    | '/e/$slug/completo'
    | '/e/$slug/gracias'
    | '/e/$slug/inscripcion'
    | '/og/c/$token'
    | '/portal/eventos/$eventId'
    | '/_authenticated/eventos/'
    | '/portal/eventos/'
    | '/_authenticated/eventos/$eventId/editar'
    | '/_authenticated/eventos/$eventId/sesiones/$sessionId'
    | '/_authenticated/eventos/$eventId/sesiones/nueva'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AuthenticatedRoute: typeof AuthenticatedRouteWithChildren
  LoginRoute: typeof LoginRoute
  PortalRoute: typeof PortalRouteWithChildren
  PrivacidadRoute: typeof PrivacidadRoute
  CTokenRoute: typeof CTokenRouteWithChildren
  ESlugRoute: typeof ESlugRouteWithChildren
  FFormSlugRoute: typeof FFormSlugRoute
  TQrTokenRoute: typeof TQrTokenRoute
  OgCTokenRoute: typeof OgCTokenRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/privacidad': {
      id: '/privacidad'
      path: '/privacidad'
      fullPath: '/privacidad'
      preLoaderRoute: typeof PrivacidadRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/portal': {
      id: '/portal'
      path: '/portal'
      fullPath: '/portal'
      preLoaderRoute: typeof PortalRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/login': {
      id: '/login'
      path: '/login'
      fullPath: '/login'
      preLoaderRoute: typeof LoginRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated': {
      id: '/_authenticated'
      path: ''
      fullPath: '/'
      preLoaderRoute: typeof AuthenticatedRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/portal/': {
      id: '/portal/'
      path: '/'
      fullPath: '/portal/'
      preLoaderRoute: typeof PortalIndexRouteImport
      parentRoute: typeof PortalRoute
    }
    '/t/$qrToken': {
      id: '/t/$qrToken'
      path: '/t/$qrToken'
      fullPath: '/t/$qrToken'
      preLoaderRoute: typeof TQrTokenRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/portal/informes': {
      id: '/portal/informes'
      path: '/informes'
      fullPath: '/portal/informes'
      preLoaderRoute: typeof PortalInformesRouteImport
      parentRoute: typeof PortalRoute
    }
    '/portal/incidencias': {
      id: '/portal/incidencias'
      path: '/incidencias'
      fullPath: '/portal/incidencias'
      preLoaderRoute: typeof PortalIncidenciasRouteImport
      parentRoute: typeof PortalRoute
    }
    '/portal/eventos': {
      id: '/portal/eventos'
      path: '/eventos'
      fullPath: '/portal/eventos'
      preLoaderRoute: typeof PortalEventosRouteImport
      parentRoute: typeof PortalRoute
    }
    '/f/$formSlug': {
      id: '/f/$formSlug'
      path: '/f/$formSlug'
      fullPath: '/f/$formSlug'
      preLoaderRoute: typeof FFormSlugRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/e/$slug': {
      id: '/e/$slug'
      path: '/e/$slug'
      fullPath: '/e/$slug'
      preLoaderRoute: typeof ESlugRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/c/$token': {
      id: '/c/$token'
      path: '/c/$token'
      fullPath: '/c/$token'
      preLoaderRoute: typeof CTokenRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated/usuarios': {
      id: '/_authenticated/usuarios'
      path: '/usuarios'
      fullPath: '/usuarios'
      preLoaderRoute: typeof AuthenticatedUsuariosRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/solicitudes': {
      id: '/_authenticated/solicitudes'
      path: '/solicitudes'
      fullPath: '/solicitudes'
      preLoaderRoute: typeof AuthenticatedSolicitudesRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/sesiones': {
      id: '/_authenticated/sesiones'
      path: '/sesiones'
      fullPath: '/sesiones'
      preLoaderRoute: typeof AuthenticatedSesionesRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/personas': {
      id: '/_authenticated/personas'
      path: '/personas'
      fullPath: '/personas'
      preLoaderRoute: typeof AuthenticatedPersonasRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/logs': {
      id: '/_authenticated/logs'
      path: '/logs'
      fullPath: '/logs'
      preLoaderRoute: typeof AuthenticatedLogsRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/legal': {
      id: '/_authenticated/legal'
      path: '/legal'
      fullPath: '/legal'
      preLoaderRoute: typeof AuthenticatedLegalRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/informes': {
      id: '/_authenticated/informes'
      path: '/informes'
      fullPath: '/informes'
      preLoaderRoute: typeof AuthenticatedInformesRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/incidencias': {
      id: '/_authenticated/incidencias'
      path: '/incidencias'
      fullPath: '/incidencias'
      preLoaderRoute: typeof AuthenticatedIncidenciasRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/importaciones': {
      id: '/_authenticated/importaciones'
      path: '/importaciones'
      fullPath: '/importaciones'
      preLoaderRoute: typeof AuthenticatedImportacionesRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/diseno-entradas': {
      id: '/_authenticated/diseno-entradas'
      path: '/diseno-entradas'
      fullPath: '/diseno-entradas'
      preLoaderRoute: typeof AuthenticatedDisenoEntradasRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/dashboard': {
      id: '/_authenticated/dashboard'
      path: '/dashboard'
      fullPath: '/dashboard'
      preLoaderRoute: typeof AuthenticatedDashboardRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/control-acceso': {
      id: '/_authenticated/control-acceso'
      path: '/control-acceso'
      fullPath: '/control-acceso'
      preLoaderRoute: typeof AuthenticatedControlAccesoRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/comunicaciones': {
      id: '/_authenticated/comunicaciones'
      path: '/comunicaciones'
      fullPath: '/comunicaciones'
      preLoaderRoute: typeof AuthenticatedComunicacionesRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/clientes': {
      id: '/_authenticated/clientes'
      path: '/clientes'
      fullPath: '/clientes'
      preLoaderRoute: typeof AuthenticatedClientesRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/branding': {
      id: '/_authenticated/branding'
      path: '/branding'
      fullPath: '/branding'
      preLoaderRoute: typeof AuthenticatedBrandingRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/portal/eventos/': {
      id: '/portal/eventos/'
      path: '/'
      fullPath: '/portal/eventos/'
      preLoaderRoute: typeof PortalEventosIndexRouteImport
      parentRoute: typeof PortalEventosRoute
    }
    '/_authenticated/eventos/': {
      id: '/_authenticated/eventos/'
      path: '/eventos'
      fullPath: '/eventos/'
      preLoaderRoute: typeof AuthenticatedEventosIndexRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/portal/eventos/$eventId': {
      id: '/portal/eventos/$eventId'
      path: '/$eventId'
      fullPath: '/portal/eventos/$eventId'
      preLoaderRoute: typeof PortalEventosEventIdRouteImport
      parentRoute: typeof PortalEventosRoute
    }
    '/og/c/$token': {
      id: '/og/c/$token'
      path: '/og/c/$token'
      fullPath: '/og/c/$token'
      preLoaderRoute: typeof OgCTokenRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/e/$slug/inscripcion': {
      id: '/e/$slug/inscripcion'
      path: '/inscripcion'
      fullPath: '/e/$slug/inscripcion'
      preLoaderRoute: typeof ESlugInscripcionRouteImport
      parentRoute: typeof ESlugRoute
    }
    '/e/$slug/gracias': {
      id: '/e/$slug/gracias'
      path: '/gracias'
      fullPath: '/e/$slug/gracias'
      preLoaderRoute: typeof ESlugGraciasRouteImport
      parentRoute: typeof ESlugRoute
    }
    '/e/$slug/completo': {
      id: '/e/$slug/completo'
      path: '/completo'
      fullPath: '/e/$slug/completo'
      preLoaderRoute: typeof ESlugCompletoRouteImport
      parentRoute: typeof ESlugRoute
    }
    '/e/$slug/cerrado': {
      id: '/e/$slug/cerrado'
      path: '/cerrado'
      fullPath: '/e/$slug/cerrado'
      preLoaderRoute: typeof ESlugCerradoRouteImport
      parentRoute: typeof ESlugRoute
    }
    '/c/$token/entrada': {
      id: '/c/$token/entrada'
      path: '/entrada'
      fullPath: '/c/$token/entrada'
      preLoaderRoute: typeof CTokenEntradaRouteImport
      parentRoute: typeof CTokenRoute
    }
    '/c/$token/cancelar': {
      id: '/c/$token/cancelar'
      path: '/cancelar'
      fullPath: '/c/$token/cancelar'
      preLoaderRoute: typeof CTokenCancelarRouteImport
      parentRoute: typeof CTokenRoute
    }
    '/c/$token/cancelada': {
      id: '/c/$token/cancelada'
      path: '/cancelada'
      fullPath: '/c/$token/cancelada'
      preLoaderRoute: typeof CTokenCanceladaRouteImport
      parentRoute: typeof CTokenRoute
    }
    '/_authenticated/solicitudes/$participantId': {
      id: '/_authenticated/solicitudes/$participantId'
      path: '/$participantId'
      fullPath: '/solicitudes/$participantId'
      preLoaderRoute: typeof AuthenticatedSolicitudesParticipantIdRouteImport
      parentRoute: typeof AuthenticatedSolicitudesRoute
    }
    '/_authenticated/informes/$eventId': {
      id: '/_authenticated/informes/$eventId'
      path: '/$eventId'
      fullPath: '/informes/$eventId'
      preLoaderRoute: typeof AuthenticatedInformesEventIdRouteImport
      parentRoute: typeof AuthenticatedInformesRoute
    }
    '/_authenticated/importaciones/nueva': {
      id: '/_authenticated/importaciones/nueva'
      path: '/nueva'
      fullPath: '/importaciones/nueva'
      preLoaderRoute: typeof AuthenticatedImportacionesNuevaRouteImport
      parentRoute: typeof AuthenticatedImportacionesRoute
    }
    '/_authenticated/importaciones/$batchId': {
      id: '/_authenticated/importaciones/$batchId'
      path: '/$batchId'
      fullPath: '/importaciones/$batchId'
      preLoaderRoute: typeof AuthenticatedImportacionesBatchIdRouteImport
      parentRoute: typeof AuthenticatedImportacionesRoute
    }
    '/_authenticated/eventos/nuevo': {
      id: '/_authenticated/eventos/nuevo'
      path: '/eventos/nuevo'
      fullPath: '/eventos/nuevo'
      preLoaderRoute: typeof AuthenticatedEventosNuevoRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/eventos/$eventId': {
      id: '/_authenticated/eventos/$eventId'
      path: '/eventos/$eventId'
      fullPath: '/eventos/$eventId'
      preLoaderRoute: typeof AuthenticatedEventosEventIdRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/control-acceso/$sessionId': {
      id: '/_authenticated/control-acceso/$sessionId'
      path: '/$sessionId'
      fullPath: '/control-acceso/$sessionId'
      preLoaderRoute: typeof AuthenticatedControlAccesoSessionIdRouteImport
      parentRoute: typeof AuthenticatedControlAccesoRoute
    }
    '/_authenticated/comunicaciones/envio': {
      id: '/_authenticated/comunicaciones/envio'
      path: '/envio'
      fullPath: '/comunicaciones/envio'
      preLoaderRoute: typeof AuthenticatedComunicacionesEnvioRouteImport
      parentRoute: typeof AuthenticatedComunicacionesRoute
    }
    '/_authenticated/comunicaciones/cola': {
      id: '/_authenticated/comunicaciones/cola'
      path: '/cola'
      fullPath: '/comunicaciones/cola'
      preLoaderRoute: typeof AuthenticatedComunicacionesColaRouteImport
      parentRoute: typeof AuthenticatedComunicacionesRoute
    }
    '/_authenticated/eventos/$eventId/editar': {
      id: '/_authenticated/eventos/$eventId/editar'
      path: '/editar'
      fullPath: '/eventos/$eventId/editar'
      preLoaderRoute: typeof AuthenticatedEventosEventIdEditarRouteImport
      parentRoute: typeof AuthenticatedEventosEventIdRoute
    }
    '/_authenticated/eventos/$eventId/sesiones/nueva': {
      id: '/_authenticated/eventos/$eventId/sesiones/nueva'
      path: '/sesiones/nueva'
      fullPath: '/eventos/$eventId/sesiones/nueva'
      preLoaderRoute: typeof AuthenticatedEventosEventIdSesionesNuevaRouteImport
      parentRoute: typeof AuthenticatedEventosEventIdRoute
    }
    '/_authenticated/eventos/$eventId/sesiones/$sessionId': {
      id: '/_authenticated/eventos/$eventId/sesiones/$sessionId'
      path: '/sesiones/$sessionId'
      fullPath: '/eventos/$eventId/sesiones/$sessionId'
      preLoaderRoute: typeof AuthenticatedEventosEventIdSesionesSessionIdRouteImport
      parentRoute: typeof AuthenticatedEventosEventIdRoute
    }
  }
}

interface AuthenticatedComunicacionesRouteChildren {
  AuthenticatedComunicacionesColaRoute: typeof AuthenticatedComunicacionesColaRoute
  AuthenticatedComunicacionesEnvioRoute: typeof AuthenticatedComunicacionesEnvioRoute
}

const AuthenticatedComunicacionesRouteChildren: AuthenticatedComunicacionesRouteChildren =
  {
    AuthenticatedComunicacionesColaRoute: AuthenticatedComunicacionesColaRoute,
    AuthenticatedComunicacionesEnvioRoute:
      AuthenticatedComunicacionesEnvioRoute,
  }

const AuthenticatedComunicacionesRouteWithChildren =
  AuthenticatedComunicacionesRoute._addFileChildren(
    AuthenticatedComunicacionesRouteChildren,
  )

interface AuthenticatedControlAccesoRouteChildren {
  AuthenticatedControlAccesoSessionIdRoute: typeof AuthenticatedControlAccesoSessionIdRoute
}

const AuthenticatedControlAccesoRouteChildren: AuthenticatedControlAccesoRouteChildren =
  {
    AuthenticatedControlAccesoSessionIdRoute:
      AuthenticatedControlAccesoSessionIdRoute,
  }

const AuthenticatedControlAccesoRouteWithChildren =
  AuthenticatedControlAccesoRoute._addFileChildren(
    AuthenticatedControlAccesoRouteChildren,
  )

interface AuthenticatedImportacionesRouteChildren {
  AuthenticatedImportacionesBatchIdRoute: typeof AuthenticatedImportacionesBatchIdRoute
  AuthenticatedImportacionesNuevaRoute: typeof AuthenticatedImportacionesNuevaRoute
}

const AuthenticatedImportacionesRouteChildren: AuthenticatedImportacionesRouteChildren =
  {
    AuthenticatedImportacionesBatchIdRoute:
      AuthenticatedImportacionesBatchIdRoute,
    AuthenticatedImportacionesNuevaRoute: AuthenticatedImportacionesNuevaRoute,
  }

const AuthenticatedImportacionesRouteWithChildren =
  AuthenticatedImportacionesRoute._addFileChildren(
    AuthenticatedImportacionesRouteChildren,
  )

interface AuthenticatedInformesRouteChildren {
  AuthenticatedInformesEventIdRoute: typeof AuthenticatedInformesEventIdRoute
}

const AuthenticatedInformesRouteChildren: AuthenticatedInformesRouteChildren = {
  AuthenticatedInformesEventIdRoute: AuthenticatedInformesEventIdRoute,
}

const AuthenticatedInformesRouteWithChildren =
  AuthenticatedInformesRoute._addFileChildren(
    AuthenticatedInformesRouteChildren,
  )

interface AuthenticatedSolicitudesRouteChildren {
  AuthenticatedSolicitudesParticipantIdRoute: typeof AuthenticatedSolicitudesParticipantIdRoute
}

const AuthenticatedSolicitudesRouteChildren: AuthenticatedSolicitudesRouteChildren =
  {
    AuthenticatedSolicitudesParticipantIdRoute:
      AuthenticatedSolicitudesParticipantIdRoute,
  }

const AuthenticatedSolicitudesRouteWithChildren =
  AuthenticatedSolicitudesRoute._addFileChildren(
    AuthenticatedSolicitudesRouteChildren,
  )

interface AuthenticatedEventosEventIdRouteChildren {
  AuthenticatedEventosEventIdEditarRoute: typeof AuthenticatedEventosEventIdEditarRoute
  AuthenticatedEventosEventIdSesionesSessionIdRoute: typeof AuthenticatedEventosEventIdSesionesSessionIdRoute
  AuthenticatedEventosEventIdSesionesNuevaRoute: typeof AuthenticatedEventosEventIdSesionesNuevaRoute
}

const AuthenticatedEventosEventIdRouteChildren: AuthenticatedEventosEventIdRouteChildren =
  {
    AuthenticatedEventosEventIdEditarRoute:
      AuthenticatedEventosEventIdEditarRoute,
    AuthenticatedEventosEventIdSesionesSessionIdRoute:
      AuthenticatedEventosEventIdSesionesSessionIdRoute,
    AuthenticatedEventosEventIdSesionesNuevaRoute:
      AuthenticatedEventosEventIdSesionesNuevaRoute,
  }

const AuthenticatedEventosEventIdRouteWithChildren =
  AuthenticatedEventosEventIdRoute._addFileChildren(
    AuthenticatedEventosEventIdRouteChildren,
  )

interface AuthenticatedRouteChildren {
  AuthenticatedBrandingRoute: typeof AuthenticatedBrandingRoute
  AuthenticatedClientesRoute: typeof AuthenticatedClientesRoute
  AuthenticatedComunicacionesRoute: typeof AuthenticatedComunicacionesRouteWithChildren
  AuthenticatedControlAccesoRoute: typeof AuthenticatedControlAccesoRouteWithChildren
  AuthenticatedDashboardRoute: typeof AuthenticatedDashboardRoute
  AuthenticatedDisenoEntradasRoute: typeof AuthenticatedDisenoEntradasRoute
  AuthenticatedImportacionesRoute: typeof AuthenticatedImportacionesRouteWithChildren
  AuthenticatedIncidenciasRoute: typeof AuthenticatedIncidenciasRoute
  AuthenticatedInformesRoute: typeof AuthenticatedInformesRouteWithChildren
  AuthenticatedLegalRoute: typeof AuthenticatedLegalRoute
  AuthenticatedLogsRoute: typeof AuthenticatedLogsRoute
  AuthenticatedPersonasRoute: typeof AuthenticatedPersonasRoute
  AuthenticatedSesionesRoute: typeof AuthenticatedSesionesRoute
  AuthenticatedSolicitudesRoute: typeof AuthenticatedSolicitudesRouteWithChildren
  AuthenticatedUsuariosRoute: typeof AuthenticatedUsuariosRoute
  AuthenticatedEventosEventIdRoute: typeof AuthenticatedEventosEventIdRouteWithChildren
  AuthenticatedEventosNuevoRoute: typeof AuthenticatedEventosNuevoRoute
  AuthenticatedEventosIndexRoute: typeof AuthenticatedEventosIndexRoute
}

const AuthenticatedRouteChildren: AuthenticatedRouteChildren = {
  AuthenticatedBrandingRoute: AuthenticatedBrandingRoute,
  AuthenticatedClientesRoute: AuthenticatedClientesRoute,
  AuthenticatedComunicacionesRoute:
    AuthenticatedComunicacionesRouteWithChildren,
  AuthenticatedControlAccesoRoute: AuthenticatedControlAccesoRouteWithChildren,
  AuthenticatedDashboardRoute: AuthenticatedDashboardRoute,
  AuthenticatedDisenoEntradasRoute: AuthenticatedDisenoEntradasRoute,
  AuthenticatedImportacionesRoute: AuthenticatedImportacionesRouteWithChildren,
  AuthenticatedIncidenciasRoute: AuthenticatedIncidenciasRoute,
  AuthenticatedInformesRoute: AuthenticatedInformesRouteWithChildren,
  AuthenticatedLegalRoute: AuthenticatedLegalRoute,
  AuthenticatedLogsRoute: AuthenticatedLogsRoute,
  AuthenticatedPersonasRoute: AuthenticatedPersonasRoute,
  AuthenticatedSesionesRoute: AuthenticatedSesionesRoute,
  AuthenticatedSolicitudesRoute: AuthenticatedSolicitudesRouteWithChildren,
  AuthenticatedUsuariosRoute: AuthenticatedUsuariosRoute,
  AuthenticatedEventosEventIdRoute:
    AuthenticatedEventosEventIdRouteWithChildren,
  AuthenticatedEventosNuevoRoute: AuthenticatedEventosNuevoRoute,
  AuthenticatedEventosIndexRoute: AuthenticatedEventosIndexRoute,
}

const AuthenticatedRouteWithChildren = AuthenticatedRoute._addFileChildren(
  AuthenticatedRouteChildren,
)

interface PortalEventosRouteChildren {
  PortalEventosEventIdRoute: typeof PortalEventosEventIdRoute
  PortalEventosIndexRoute: typeof PortalEventosIndexRoute
}

const PortalEventosRouteChildren: PortalEventosRouteChildren = {
  PortalEventosEventIdRoute: PortalEventosEventIdRoute,
  PortalEventosIndexRoute: PortalEventosIndexRoute,
}

const PortalEventosRouteWithChildren = PortalEventosRoute._addFileChildren(
  PortalEventosRouteChildren,
)

interface PortalRouteChildren {
  PortalEventosRoute: typeof PortalEventosRouteWithChildren
  PortalIncidenciasRoute: typeof PortalIncidenciasRoute
  PortalInformesRoute: typeof PortalInformesRoute
  PortalIndexRoute: typeof PortalIndexRoute
}

const PortalRouteChildren: PortalRouteChildren = {
  PortalEventosRoute: PortalEventosRouteWithChildren,
  PortalIncidenciasRoute: PortalIncidenciasRoute,
  PortalInformesRoute: PortalInformesRoute,
  PortalIndexRoute: PortalIndexRoute,
}

const PortalRouteWithChildren =
  PortalRoute._addFileChildren(PortalRouteChildren)

interface CTokenRouteChildren {
  CTokenCanceladaRoute: typeof CTokenCanceladaRoute
  CTokenCancelarRoute: typeof CTokenCancelarRoute
  CTokenEntradaRoute: typeof CTokenEntradaRoute
}

const CTokenRouteChildren: CTokenRouteChildren = {
  CTokenCanceladaRoute: CTokenCanceladaRoute,
  CTokenCancelarRoute: CTokenCancelarRoute,
  CTokenEntradaRoute: CTokenEntradaRoute,
}

const CTokenRouteWithChildren =
  CTokenRoute._addFileChildren(CTokenRouteChildren)

interface ESlugRouteChildren {
  ESlugCerradoRoute: typeof ESlugCerradoRoute
  ESlugCompletoRoute: typeof ESlugCompletoRoute
  ESlugGraciasRoute: typeof ESlugGraciasRoute
  ESlugInscripcionRoute: typeof ESlugInscripcionRoute
}

const ESlugRouteChildren: ESlugRouteChildren = {
  ESlugCerradoRoute: ESlugCerradoRoute,
  ESlugCompletoRoute: ESlugCompletoRoute,
  ESlugGraciasRoute: ESlugGraciasRoute,
  ESlugInscripcionRoute: ESlugInscripcionRoute,
}

const ESlugRouteWithChildren = ESlugRoute._addFileChildren(ESlugRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AuthenticatedRoute: AuthenticatedRouteWithChildren,
  LoginRoute: LoginRoute,
  PortalRoute: PortalRouteWithChildren,
  PrivacidadRoute: PrivacidadRoute,
  CTokenRoute: CTokenRouteWithChildren,
  ESlugRoute: ESlugRouteWithChildren,
  FFormSlugRoute: FFormSlugRoute,
  TQrTokenRoute: TQrTokenRoute,
  OgCTokenRoute: OgCTokenRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
