/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as LoginRouteImport } from './routes/login'
import { Route as AuthenticatedRouteImport } from './routes/_authenticated'
import { Route as IndexRouteImport } from './routes/index'
import { Route as ESlugRouteImport } from './routes/e.$slug'
import { Route as AuthenticatedUsuariosRouteImport } from './routes/_authenticated/usuarios'
import { Route as AuthenticatedSolicitudesRouteImport } from './routes/_authenticated/solicitudes'
import { Route as AuthenticatedSesionesRouteImport } from './routes/_authenticated/sesiones'
import { Route as AuthenticatedPersonasRouteImport } from './routes/_authenticated/personas'
import { Route as AuthenticatedLogsRouteImport } from './routes/_authenticated/logs'
import { Route as AuthenticatedLegalRouteImport } from './routes/_authenticated/legal'
import { Route as AuthenticatedInformesRouteImport } from './routes/_authenticated/informes'
import { Route as AuthenticatedIncidenciasRouteImport } from './routes/_authenticated/incidencias'
import { Route as AuthenticatedImportacionesRouteImport } from './routes/_authenticated/importaciones'
import { Route as AuthenticatedEventosRouteImport } from './routes/_authenticated/eventos'
import { Route as AuthenticatedDashboardRouteImport } from './routes/_authenticated/dashboard'
import { Route as AuthenticatedControlAccesoRouteImport } from './routes/_authenticated/control-acceso'
import { Route as AuthenticatedComunicacionesRouteImport } from './routes/_authenticated/comunicaciones'
import { Route as AuthenticatedClientesRouteImport } from './routes/_authenticated/clientes'
import { Route as AuthenticatedBrandingRouteImport } from './routes/_authenticated/branding'
import { Route as ESlugCompletoRouteImport } from './routes/e.$slug.completo'
import { Route as ESlugCerradoRouteImport } from './routes/e.$slug.cerrado'
import { Route as AuthenticatedEventosNuevoRouteImport } from './routes/_authenticated/eventos.nuevo'
import { Route as AuthenticatedEventosEventIdRouteImport } from './routes/_authenticated/eventos.$eventId'
import { Route as AuthenticatedEventosEventIdEditarRouteImport } from './routes/_authenticated/eventos.$eventId.editar'
import { Route as AuthenticatedEventosEventIdSesionesNuevaRouteImport } from './routes/_authenticated/eventos.$eventId.sesiones.nueva'
import { Route as AuthenticatedEventosEventIdSesionesSessionIdRouteImport } from './routes/_authenticated/eventos.$eventId.sesiones.$sessionId'

const LoginRoute = LoginRouteImport.update({
  id: '/login',
  path: '/login',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthenticatedRoute = AuthenticatedRouteImport.update({
  id: '/_authenticated',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const ESlugRoute = ESlugRouteImport.update({
  id: '/e/$slug',
  path: '/e/$slug',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthenticatedUsuariosRoute = AuthenticatedUsuariosRouteImport.update({
  id: '/usuarios',
  path: '/usuarios',
  getParentRoute: () => AuthenticatedRoute,
} as any)
const AuthenticatedSolicitudesRoute =
  AuthenticatedSolicitudesRouteImport.update({
    id: '/solicitudes',
    path: '/solicitudes',
    getParentRoute: () => AuthenticatedRoute,
  } as any)
const AuthenticatedSesionesRoute = AuthenticatedSesionesRouteImport.update({
  id: '/sesiones',
  path: '/sesiones',
  getParentRoute: () => AuthenticatedRoute,
} as any)
const AuthenticatedPersonasRoute = AuthenticatedPersonasRouteImport.update({
  id: '/personas',
  path: '/personas',
  getParentRoute: () => AuthenticatedRoute,
} as any)
const AuthenticatedLogsRoute = AuthenticatedLogsRouteImport.update({
  id: '/logs',
  path: '/logs',
  getParentRoute: () => AuthenticatedRoute,
} as any)
const AuthenticatedLegalRoute = AuthenticatedLegalRouteImport.update({
  id: '/legal',
  path: '/legal',
  getParentRoute: () => AuthenticatedRoute,
} as any)
const AuthenticatedInformesRoute = AuthenticatedInformesRouteImport.update({
  id: '/informes',
  path: '/informes',
  getParentRoute: () => AuthenticatedRoute,
} as any)
const AuthenticatedIncidenciasRoute =
  AuthenticatedIncidenciasRouteImport.update({
    id: '/incidencias',
    path: '/incidencias',
    getParentRoute: () => AuthenticatedRoute,
  } as any)
const AuthenticatedImportacionesRoute =
  AuthenticatedImportacionesRouteImport.update({
    id: '/importaciones',
    path: '/importaciones',
    getParentRoute: () => AuthenticatedRoute,
  } as any)
const AuthenticatedEventosRoute = AuthenticatedEventosRouteImport.update({
  id: '/eventos',
  path: '/eventos',
  getParentRoute: () => AuthenticatedRoute,
} as any)
const AuthenticatedDashboardRoute = AuthenticatedDashboardRouteImport.update({
  id: '/dashboard',
  path: '/dashboard',
  getParentRoute: () => AuthenticatedRoute,
} as any)
const AuthenticatedControlAccesoRoute =
  AuthenticatedControlAccesoRouteImport.update({
    id: '/control-acceso',
    path: '/control-acceso',
    getParentRoute: () => AuthenticatedRoute,
  } as any)
const AuthenticatedComunicacionesRoute =
  AuthenticatedComunicacionesRouteImport.update({
    id: '/comunicaciones',
    path: '/comunicaciones',
    getParentRoute: () => AuthenticatedRoute,
  } as any)
const AuthenticatedClientesRoute = AuthenticatedClientesRouteImport.update({
  id: '/clientes',
  path: '/clientes',
  getParentRoute: () => AuthenticatedRoute,
} as any)
const AuthenticatedBrandingRoute = AuthenticatedBrandingRouteImport.update({
  id: '/branding',
  path: '/branding',
  getParentRoute: () => AuthenticatedRoute,
} as any)
const ESlugCompletoRoute = ESlugCompletoRouteImport.update({
  id: '/completo',
  path: '/completo',
  getParentRoute: () => ESlugRoute,
} as any)
const ESlugCerradoRoute = ESlugCerradoRouteImport.update({
  id: '/cerrado',
  path: '/cerrado',
  getParentRoute: () => ESlugRoute,
} as any)
const AuthenticatedEventosNuevoRoute =
  AuthenticatedEventosNuevoRouteImport.update({
    id: '/nuevo',
    path: '/nuevo',
    getParentRoute: () => AuthenticatedEventosRoute,
  } as any)
const AuthenticatedEventosEventIdRoute =
  AuthenticatedEventosEventIdRouteImport.update({
    id: '/$eventId',
    path: '/$eventId',
    getParentRoute: () => AuthenticatedEventosRoute,
  } as any)
const AuthenticatedEventosEventIdEditarRoute =
  AuthenticatedEventosEventIdEditarRouteImport.update({
    id: '/editar',
    path: '/editar',
    getParentRoute: () => AuthenticatedEventosEventIdRoute,
  } as any)
const AuthenticatedEventosEventIdSesionesNuevaRoute =
  AuthenticatedEventosEventIdSesionesNuevaRouteImport.update({
    id: '/sesiones/nueva',
    path: '/sesiones/nueva',
    getParentRoute: () => AuthenticatedEventosEventIdRoute,
  } as any)
const AuthenticatedEventosEventIdSesionesSessionIdRoute =
  AuthenticatedEventosEventIdSesionesSessionIdRouteImport.update({
    id: '/sesiones/$sessionId',
    path: '/sesiones/$sessionId',
    getParentRoute: () => AuthenticatedEventosEventIdRoute,
  } as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/login': typeof LoginRoute
  '/branding': typeof AuthenticatedBrandingRoute
  '/clientes': typeof AuthenticatedClientesRoute
  '/comunicaciones': typeof AuthenticatedComunicacionesRoute
  '/control-acceso': typeof AuthenticatedControlAccesoRoute
  '/dashboard': typeof AuthenticatedDashboardRoute
  '/eventos': typeof AuthenticatedEventosRouteWithChildren
  '/importaciones': typeof AuthenticatedImportacionesRoute
  '/incidencias': typeof AuthenticatedIncidenciasRoute
  '/informes': typeof AuthenticatedInformesRoute
  '/legal': typeof AuthenticatedLegalRoute
  '/logs': typeof AuthenticatedLogsRoute
  '/personas': typeof AuthenticatedPersonasRoute
  '/sesiones': typeof AuthenticatedSesionesRoute
  '/solicitudes': typeof AuthenticatedSolicitudesRoute
  '/usuarios': typeof AuthenticatedUsuariosRoute
  '/e/$slug': typeof ESlugRouteWithChildren
  '/eventos/$eventId': typeof AuthenticatedEventosEventIdRouteWithChildren
  '/eventos/nuevo': typeof AuthenticatedEventosNuevoRoute
  '/e/$slug/cerrado': typeof ESlugCerradoRoute
  '/e/$slug/completo': typeof ESlugCompletoRoute
  '/eventos/$eventId/editar': typeof AuthenticatedEventosEventIdEditarRoute
  '/eventos/$eventId/sesiones/$sessionId': typeof AuthenticatedEventosEventIdSesionesSessionIdRoute
  '/eventos/$eventId/sesiones/nueva': typeof AuthenticatedEventosEventIdSesionesNuevaRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/login': typeof LoginRoute
  '/branding': typeof AuthenticatedBrandingRoute
  '/clientes': typeof AuthenticatedClientesRoute
  '/comunicaciones': typeof AuthenticatedComunicacionesRoute
  '/control-acceso': typeof AuthenticatedControlAccesoRoute
  '/dashboard': typeof AuthenticatedDashboardRoute
  '/eventos': typeof AuthenticatedEventosRouteWithChildren
  '/importaciones': typeof AuthenticatedImportacionesRoute
  '/incidencias': typeof AuthenticatedIncidenciasRoute
  '/informes': typeof AuthenticatedInformesRoute
  '/legal': typeof AuthenticatedLegalRoute
  '/logs': typeof AuthenticatedLogsRoute
  '/personas': typeof AuthenticatedPersonasRoute
  '/sesiones': typeof AuthenticatedSesionesRoute
  '/solicitudes': typeof AuthenticatedSolicitudesRoute
  '/usuarios': typeof AuthenticatedUsuariosRoute
  '/e/$slug': typeof ESlugRouteWithChildren
  '/eventos/$eventId': typeof AuthenticatedEventosEventIdRouteWithChildren
  '/eventos/nuevo': typeof AuthenticatedEventosNuevoRoute
  '/e/$slug/cerrado': typeof ESlugCerradoRoute
  '/e/$slug/completo': typeof ESlugCompletoRoute
  '/eventos/$eventId/editar': typeof AuthenticatedEventosEventIdEditarRoute
  '/eventos/$eventId/sesiones/$sessionId': typeof AuthenticatedEventosEventIdSesionesSessionIdRoute
  '/eventos/$eventId/sesiones/nueva': typeof AuthenticatedEventosEventIdSesionesNuevaRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/_authenticated': typeof AuthenticatedRouteWithChildren
  '/login': typeof LoginRoute
  '/_authenticated/branding': typeof AuthenticatedBrandingRoute
  '/_authenticated/clientes': typeof AuthenticatedClientesRoute
  '/_authenticated/comunicaciones': typeof AuthenticatedComunicacionesRoute
  '/_authenticated/control-acceso': typeof AuthenticatedControlAccesoRoute
  '/_authenticated/dashboard': typeof AuthenticatedDashboardRoute
  '/_authenticated/eventos': typeof AuthenticatedEventosRouteWithChildren
  '/_authenticated/importaciones': typeof AuthenticatedImportacionesRoute
  '/_authenticated/incidencias': typeof AuthenticatedIncidenciasRoute
  '/_authenticated/informes': typeof AuthenticatedInformesRoute
  '/_authenticated/legal': typeof AuthenticatedLegalRoute
  '/_authenticated/logs': typeof AuthenticatedLogsRoute
  '/_authenticated/personas': typeof AuthenticatedPersonasRoute
  '/_authenticated/sesiones': typeof AuthenticatedSesionesRoute
  '/_authenticated/solicitudes': typeof AuthenticatedSolicitudesRoute
  '/_authenticated/usuarios': typeof AuthenticatedUsuariosRoute
  '/e/$slug': typeof ESlugRouteWithChildren
  '/_authenticated/eventos/$eventId': typeof AuthenticatedEventosEventIdRouteWithChildren
  '/_authenticated/eventos/nuevo': typeof AuthenticatedEventosNuevoRoute
  '/e/$slug/cerrado': typeof ESlugCerradoRoute
  '/e/$slug/completo': typeof ESlugCompletoRoute
  '/_authenticated/eventos/$eventId/editar': typeof AuthenticatedEventosEventIdEditarRoute
  '/_authenticated/eventos/$eventId/sesiones/$sessionId': typeof AuthenticatedEventosEventIdSesionesSessionIdRoute
  '/_authenticated/eventos/$eventId/sesiones/nueva': typeof AuthenticatedEventosEventIdSesionesNuevaRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/login'
    | '/branding'
    | '/clientes'
    | '/comunicaciones'
    | '/control-acceso'
    | '/dashboard'
    | '/eventos'
    | '/importaciones'
    | '/incidencias'
    | '/informes'
    | '/legal'
    | '/logs'
    | '/personas'
    | '/sesiones'
    | '/solicitudes'
    | '/usuarios'
    | '/e/$slug'
    | '/eventos/$eventId'
    | '/eventos/nuevo'
    | '/e/$slug/cerrado'
    | '/e/$slug/completo'
    | '/eventos/$eventId/editar'
    | '/eventos/$eventId/sesiones/$sessionId'
    | '/eventos/$eventId/sesiones/nueva'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/login'
    | '/branding'
    | '/clientes'
    | '/comunicaciones'
    | '/control-acceso'
    | '/dashboard'
    | '/eventos'
    | '/importaciones'
    | '/incidencias'
    | '/informes'
    | '/legal'
    | '/logs'
    | '/personas'
    | '/sesiones'
    | '/solicitudes'
    | '/usuarios'
    | '/e/$slug'
    | '/eventos/$eventId'
    | '/eventos/nuevo'
    | '/e/$slug/cerrado'
    | '/e/$slug/completo'
    | '/eventos/$eventId/editar'
    | '/eventos/$eventId/sesiones/$sessionId'
    | '/eventos/$eventId/sesiones/nueva'
  id:
    | '__root__'
    | '/'
    | '/_authenticated'
    | '/login'
    | '/_authenticated/branding'
    | '/_authenticated/clientes'
    | '/_authenticated/comunicaciones'
    | '/_authenticated/control-acceso'
    | '/_authenticated/dashboard'
    | '/_authenticated/eventos'
    | '/_authenticated/importaciones'
    | '/_authenticated/incidencias'
    | '/_authenticated/informes'
    | '/_authenticated/legal'
    | '/_authenticated/logs'
    | '/_authenticated/personas'
    | '/_authenticated/sesiones'
    | '/_authenticated/solicitudes'
    | '/_authenticated/usuarios'
    | '/e/$slug'
    | '/_authenticated/eventos/$eventId'
    | '/_authenticated/eventos/nuevo'
    | '/e/$slug/cerrado'
    | '/e/$slug/completo'
    | '/_authenticated/eventos/$eventId/editar'
    | '/_authenticated/eventos/$eventId/sesiones/$sessionId'
    | '/_authenticated/eventos/$eventId/sesiones/nueva'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AuthenticatedRoute: typeof AuthenticatedRouteWithChildren
  LoginRoute: typeof LoginRoute
  ESlugRoute: typeof ESlugRouteWithChildren
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/login': {
      id: '/login'
      path: '/login'
      fullPath: '/login'
      preLoaderRoute: typeof LoginRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated': {
      id: '/_authenticated'
      path: ''
      fullPath: '/'
      preLoaderRoute: typeof AuthenticatedRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/e/$slug': {
      id: '/e/$slug'
      path: '/e/$slug'
      fullPath: '/e/$slug'
      preLoaderRoute: typeof ESlugRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated/usuarios': {
      id: '/_authenticated/usuarios'
      path: '/usuarios'
      fullPath: '/usuarios'
      preLoaderRoute: typeof AuthenticatedUsuariosRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/solicitudes': {
      id: '/_authenticated/solicitudes'
      path: '/solicitudes'
      fullPath: '/solicitudes'
      preLoaderRoute: typeof AuthenticatedSolicitudesRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/sesiones': {
      id: '/_authenticated/sesiones'
      path: '/sesiones'
      fullPath: '/sesiones'
      preLoaderRoute: typeof AuthenticatedSesionesRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/personas': {
      id: '/_authenticated/personas'
      path: '/personas'
      fullPath: '/personas'
      preLoaderRoute: typeof AuthenticatedPersonasRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/logs': {
      id: '/_authenticated/logs'
      path: '/logs'
      fullPath: '/logs'
      preLoaderRoute: typeof AuthenticatedLogsRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/legal': {
      id: '/_authenticated/legal'
      path: '/legal'
      fullPath: '/legal'
      preLoaderRoute: typeof AuthenticatedLegalRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/informes': {
      id: '/_authenticated/informes'
      path: '/informes'
      fullPath: '/informes'
      preLoaderRoute: typeof AuthenticatedInformesRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/incidencias': {
      id: '/_authenticated/incidencias'
      path: '/incidencias'
      fullPath: '/incidencias'
      preLoaderRoute: typeof AuthenticatedIncidenciasRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/importaciones': {
      id: '/_authenticated/importaciones'
      path: '/importaciones'
      fullPath: '/importaciones'
      preLoaderRoute: typeof AuthenticatedImportacionesRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/eventos': {
      id: '/_authenticated/eventos'
      path: '/eventos'
      fullPath: '/eventos'
      preLoaderRoute: typeof AuthenticatedEventosRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/dashboard': {
      id: '/_authenticated/dashboard'
      path: '/dashboard'
      fullPath: '/dashboard'
      preLoaderRoute: typeof AuthenticatedDashboardRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/control-acceso': {
      id: '/_authenticated/control-acceso'
      path: '/control-acceso'
      fullPath: '/control-acceso'
      preLoaderRoute: typeof AuthenticatedControlAccesoRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/comunicaciones': {
      id: '/_authenticated/comunicaciones'
      path: '/comunicaciones'
      fullPath: '/comunicaciones'
      preLoaderRoute: typeof AuthenticatedComunicacionesRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/clientes': {
      id: '/_authenticated/clientes'
      path: '/clientes'
      fullPath: '/clientes'
      preLoaderRoute: typeof AuthenticatedClientesRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/branding': {
      id: '/_authenticated/branding'
      path: '/branding'
      fullPath: '/branding'
      preLoaderRoute: typeof AuthenticatedBrandingRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/e/$slug/completo': {
      id: '/e/$slug/completo'
      path: '/completo'
      fullPath: '/e/$slug/completo'
      preLoaderRoute: typeof ESlugCompletoRouteImport
      parentRoute: typeof ESlugRoute
    }
    '/e/$slug/cerrado': {
      id: '/e/$slug/cerrado'
      path: '/cerrado'
      fullPath: '/e/$slug/cerrado'
      preLoaderRoute: typeof ESlugCerradoRouteImport
      parentRoute: typeof ESlugRoute
    }
    '/_authenticated/eventos/nuevo': {
      id: '/_authenticated/eventos/nuevo'
      path: '/nuevo'
      fullPath: '/eventos/nuevo'
      preLoaderRoute: typeof AuthenticatedEventosNuevoRouteImport
      parentRoute: typeof AuthenticatedEventosRoute
    }
    '/_authenticated/eventos/$eventId': {
      id: '/_authenticated/eventos/$eventId'
      path: '/$eventId'
      fullPath: '/eventos/$eventId'
      preLoaderRoute: typeof AuthenticatedEventosEventIdRouteImport
      parentRoute: typeof AuthenticatedEventosRoute
    }
    '/_authenticated/eventos/$eventId/editar': {
      id: '/_authenticated/eventos/$eventId/editar'
      path: '/editar'
      fullPath: '/eventos/$eventId/editar'
      preLoaderRoute: typeof AuthenticatedEventosEventIdEditarRouteImport
      parentRoute: typeof AuthenticatedEventosEventIdRoute
    }
    '/_authenticated/eventos/$eventId/sesiones/nueva': {
      id: '/_authenticated/eventos/$eventId/sesiones/nueva'
      path: '/sesiones/nueva'
      fullPath: '/eventos/$eventId/sesiones/nueva'
      preLoaderRoute: typeof AuthenticatedEventosEventIdSesionesNuevaRouteImport
      parentRoute: typeof AuthenticatedEventosEventIdRoute
    }
    '/_authenticated/eventos/$eventId/sesiones/$sessionId': {
      id: '/_authenticated/eventos/$eventId/sesiones/$sessionId'
      path: '/sesiones/$sessionId'
      fullPath: '/eventos/$eventId/sesiones/$sessionId'
      preLoaderRoute: typeof AuthenticatedEventosEventIdSesionesSessionIdRouteImport
      parentRoute: typeof AuthenticatedEventosEventIdRoute
    }
  }
}

interface AuthenticatedEventosEventIdRouteChildren {
  AuthenticatedEventosEventIdEditarRoute: typeof AuthenticatedEventosEventIdEditarRoute
  AuthenticatedEventosEventIdSesionesSessionIdRoute: typeof AuthenticatedEventosEventIdSesionesSessionIdRoute
  AuthenticatedEventosEventIdSesionesNuevaRoute: typeof AuthenticatedEventosEventIdSesionesNuevaRoute
}

const AuthenticatedEventosEventIdRouteChildren: AuthenticatedEventosEventIdRouteChildren =
  {
    AuthenticatedEventosEventIdEditarRoute:
      AuthenticatedEventosEventIdEditarRoute,
    AuthenticatedEventosEventIdSesionesSessionIdRoute:
      AuthenticatedEventosEventIdSesionesSessionIdRoute,
    AuthenticatedEventosEventIdSesionesNuevaRoute:
      AuthenticatedEventosEventIdSesionesNuevaRoute,
  }

const AuthenticatedEventosEventIdRouteWithChildren =
  AuthenticatedEventosEventIdRoute._addFileChildren(
    AuthenticatedEventosEventIdRouteChildren,
  )

interface AuthenticatedEventosRouteChildren {
  AuthenticatedEventosEventIdRoute: typeof AuthenticatedEventosEventIdRouteWithChildren
  AuthenticatedEventosNuevoRoute: typeof AuthenticatedEventosNuevoRoute
}

const AuthenticatedEventosRouteChildren: AuthenticatedEventosRouteChildren = {
  AuthenticatedEventosEventIdRoute:
    AuthenticatedEventosEventIdRouteWithChildren,
  AuthenticatedEventosNuevoRoute: AuthenticatedEventosNuevoRoute,
}

const AuthenticatedEventosRouteWithChildren =
  AuthenticatedEventosRoute._addFileChildren(AuthenticatedEventosRouteChildren)

interface AuthenticatedRouteChildren {
  AuthenticatedBrandingRoute: typeof AuthenticatedBrandingRoute
  AuthenticatedClientesRoute: typeof AuthenticatedClientesRoute
  AuthenticatedComunicacionesRoute: typeof AuthenticatedComunicacionesRoute
  AuthenticatedControlAccesoRoute: typeof AuthenticatedControlAccesoRoute
  AuthenticatedDashboardRoute: typeof AuthenticatedDashboardRoute
  AuthenticatedEventosRoute: typeof AuthenticatedEventosRouteWithChildren
  AuthenticatedImportacionesRoute: typeof AuthenticatedImportacionesRoute
  AuthenticatedIncidenciasRoute: typeof AuthenticatedIncidenciasRoute
  AuthenticatedInformesRoute: typeof AuthenticatedInformesRoute
  AuthenticatedLegalRoute: typeof AuthenticatedLegalRoute
  AuthenticatedLogsRoute: typeof AuthenticatedLogsRoute
  AuthenticatedPersonasRoute: typeof AuthenticatedPersonasRoute
  AuthenticatedSesionesRoute: typeof AuthenticatedSesionesRoute
  AuthenticatedSolicitudesRoute: typeof AuthenticatedSolicitudesRoute
  AuthenticatedUsuariosRoute: typeof AuthenticatedUsuariosRoute
}

const AuthenticatedRouteChildren: AuthenticatedRouteChildren = {
  AuthenticatedBrandingRoute: AuthenticatedBrandingRoute,
  AuthenticatedClientesRoute: AuthenticatedClientesRoute,
  AuthenticatedComunicacionesRoute: AuthenticatedComunicacionesRoute,
  AuthenticatedControlAccesoRoute: AuthenticatedControlAccesoRoute,
  AuthenticatedDashboardRoute: AuthenticatedDashboardRoute,
  AuthenticatedEventosRoute: AuthenticatedEventosRouteWithChildren,
  AuthenticatedImportacionesRoute: AuthenticatedImportacionesRoute,
  AuthenticatedIncidenciasRoute: AuthenticatedIncidenciasRoute,
  AuthenticatedInformesRoute: AuthenticatedInformesRoute,
  AuthenticatedLegalRoute: AuthenticatedLegalRoute,
  AuthenticatedLogsRoute: AuthenticatedLogsRoute,
  AuthenticatedPersonasRoute: AuthenticatedPersonasRoute,
  AuthenticatedSesionesRoute: AuthenticatedSesionesRoute,
  AuthenticatedSolicitudesRoute: AuthenticatedSolicitudesRoute,
  AuthenticatedUsuariosRoute: AuthenticatedUsuariosRoute,
}

const AuthenticatedRouteWithChildren = AuthenticatedRoute._addFileChildren(
  AuthenticatedRouteChildren,
)

interface ESlugRouteChildren {
  ESlugCerradoRoute: typeof ESlugCerradoRoute
  ESlugCompletoRoute: typeof ESlugCompletoRoute
}

const ESlugRouteChildren: ESlugRouteChildren = {
  ESlugCerradoRoute: ESlugCerradoRoute,
  ESlugCompletoRoute: ESlugCompletoRoute,
}

const ESlugRouteWithChildren = ESlugRoute._addFileChildren(ESlugRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AuthenticatedRoute: AuthenticatedRouteWithChildren,
  LoginRoute: LoginRoute,
  ESlugRoute: ESlugRouteWithChildren,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
